### PR TITLE
feat: Final tweaks

### PR DESCRIPTION
**Pull request by AntonArtomovNM**
- Added character rotation table to the group chat
- Lots of info messages about game process
- Added /rules command to see basic rules
- Now the one player who completes their city first will get doubled bonus to their score
- Fixed Show Table feature
- Fixed small issues
- Removed unit tests project :(

### CODE REVIEW

**Comment by AntonArtomovNM** [comment]
[Show player's stats in group chat](https://trello.com/c/o1XicqXc/54-show-players-stats-in-group-chat)

**Comment by AntonArtomovNM** [comment]
[Show player's stats in group chat](https://trello.com/c/o1XicqXc/54-show-players-stats-in-group-chat)

**Comment by AntonArtomovNM** [comment]
[Remove secret player data for enemies](https://trello.com/c/iASLO5hY/58-remove-secret-player-data-for-enemies)

**Review by Panzzzerfaust — APPROVED** [review]
AND THIS IS A WORK OF ART

**Pull request merged**
