### PR TITLE
Telegram "create_lobby" and "join_lobby" commands

### PR DESCRIPTION
**Pull request by AntonArtomovNM**

### CODE REVIEW

**Review by Panzzzerfaust — APPROVED** [review]
Молодец!!

**Comment by AntonArtomovNM** [comment]
> Молодец!!

Мы молодцы!

**Comment by AntonArtomovNM** [comment]
["Create room" feature](https://trello.com/c/fNRaol0Z/31-create-room-feature)

**Comment by AntonArtomovNM** [comment]
["Join room" feature](https://trello.com/c/dAFDuVPU/32-join-room-feature)

**Pull request merged**
