### PR TITLE
feat: Added basic card and character settings, added game action class

### PR DESCRIPTION
**Pull request by AntonArtomovNM**

### CODE REVIEW

**Review by Panzzzerfaust — APPROVED** [review]
Великолепно)

**Comment by AntonArtomovNM** [comment]
[Implement GameAction](https://trello.com/c/UzEzCzFQ/25-implement-gameaction)

**Comment by AntonArtomovNM** [comment]
[Card settings & building](https://trello.com/c/srF0CS8u/23-card-settings-building)

**Comment by AntonArtomovNM** [comment]
[Character setting & building](https://trello.com/c/wKgvVtZs/24-character-setting-building)

**Pull request merged**
